version: '3.5'
services:
  backend:
    environment:
      - RAILS_ENV=${DOCKERFRONT_ENVIRONMENT}
      - RACK_ENV=${DOCKERFRONT_ENVIRONMENT}
      - RAILS_PORT=${DOCKERFRONT_RAILS_PORT}
      - DOCKERFRONT_PUBLIC_BASE_URL=http://localhost:${DOCKERFRONT_BACKEND_PORT}
      - DOCKERFRONT_REPOSITORY_NAME=${DOCKERFRONT_REPOSITORY_NAME}
      - DOCKERFRONT_API_URL=${DOCKERFRONT_API_URL}
      - DOCKERFRONT_API_USER=${DOCKERFRONT_API_USER}
      - DOCKERFRONT_API_PWD=${DOCKERFRONT_API_PWD}
    ports:
      - ${DOCKERFRONT_BACKEND_PORT}:${DOCKERFRONT_RAILS_PORT}