# try messing with stdin_open and tty to find out correct setting
version: '3.5'
services:
  backend:
    build: ../
    volumes:
      - ../:/project
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
